; HanBee

[platformio]
src_dir = src
include_dir = src
default_envs = 
    HanBeeC6

[common]
monitor_speed = 115200
lib_deps =
    ModbusMaster = https://github.com/nikito7/__ModbusMaster.git#Timeout     
    Zigbee

[env:HanBeeC6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c6-devkitc-1
board_build.partitions = zigbee_zczr_8MB.csv
board_build.filesystem = spiffs
framework = arduino

lib_deps =
    ${common.lib_deps}

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DZIGBEE_MODE_ZCZR
    -DESP32C6

; EOF
